### ISSUE TITLE
v2.0.0 no longer fails for localhost with "private IP Address" error

### ISSUE THREAD

**Issue by benasher44** [azu/request-filtering-agent#19]
Prior to v2.0.0, the agent would reject requests to a URL like `http://localhost/test` by throwing an error like "…is not allowed. Because, It is private IP address.", but now I'm getting an  ECONNREFUSED error, which implies that the request is being allowed through.

**Comment by benasher44** [comment]
I'm currently testing this on the latest node v18

**Comment by benasher44** [comment]
The issue is here:

https://github.com/azu/request-filtering-agent/blob/dbdeeb54d0278cbc44868a4b9eac8e2b659d9163/src/request-filtering-agent.ts#L141-L143

By calling end and then destroy _in the callback_, you let the connection finish and attempt to contact localhost, thereby erroring with connection refused (before destroy gets a chance to send/emit the validationError first). Instead, this worked for me locally for node 18:

```
socket.end();
socket.destroy();
```

This doesn't work for node 20 though (brings back the node internal error)

**Comment by benasher44** [comment]
I more fool proof way is probably to provide a function as the `lookup` option to `createConnection`, which would allow you to wrap `dns.lookup` and call `lookup`'s callback function with the validation error. This would allow you to stop everything at lookup time, without allowing the connection to progress further.

**Comment by benasher44** [comment]
What's strange is that I can't reproduce this in the way I would expect in the tests for this project. Hopefully the solution I provided will just put this issue to bed generally.

**Comment by azu** [comment]
Thanks for report.

> What's strange is that I can't reproduce this in the way I would expect in the tests for this project.

Indeed, the test shows "request to http://localhost:12456/ failed, reason: DNS lookup ::1(family:6, host:localhost) is not allowed. Because, It is private IP address.".

At https://github.com/azu/request-filtering-agent/pull/20 I don't think it will get worse because the test is passing.
I would like to add a test to detect this problem if possible.

**Comment by azu** [comment]
2.0.1 has been released.
Can you confirm that the problem has been resolved?

https://github.com/azu/request-filtering-agent/releases/tag/v2.0.1

**Comment by benasher44** [comment]
Already confirmed it fixed it with a local build today, but I'll doubly confirm with the released version tomorrow! I also have a hunch on how to make a test that fails on 2.0.0 (also tomorrow)

**Comment by benasher44** [comment]
Found some time :)

Confirmed 2.0.1 works, and I added test cases that fail in 2.0.0 and pass in 2.0.1 in #22
